version: '3.7'
services:
  api:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: api:1.0.0
    container_name: api
    user: 'node'
    hostname: node
    ports:
      - '3000:3000'
    restart: 'always'
    volumes:
      - $PWD/logs:/api/logs